import { select, selectOne } from './client'
export type Customer={id:string;code:string;name:string;phone:string|null;email:string|null;gstin:string|null;billingAddress:string|null;shippingAddress:string|null;state:string|null;city:string|null;stateCode?:string|null;pincode?:string|null}
export type Product={id:string;code:string;name:string;category:string;hsn:string|null;packSize:string|null;unit:string;rateMinor:number;gstRateBps:number;active:boolean;stockQty:number;reorderLevel:number;stockUnit:string;shelfLocation:string|null;costMinor:number}
type Row=Record<string,unknown>
const customerSelect='id,code,name,phone,email,gstin,billingAddress:billing_address,shippingAddress:shipping_address,state,stateCode:state_code,city,pincode'
const productSelect='id,code,name,category,hsn_code,packSize:pack_size,unit,rateMinor:default_rate_minor,gstRateBps:gst_rate_bps,active:is_active,stockQty:stock_qty,reorderLevel:reorder_level,stockUnit:stock_unit,shelfLocation:shelf_location,costMinor:cost_minor'
export async function searchCustomers(term=''):Promise<Customer[]>{const q=term.trim(),search=q?`&or=(name.ilike.*${encodeURIComponent(q)}*,code.ilike.*${encodeURIComponent(q)}*,phone.ilike.*${encodeURIComponent(q)}*,gstin.ilike.*${encodeURIComponent(q)}*,city.ilike.*${encodeURIComponent(q)}*)`:'';return(await select<Row>('customers',`select=${customerSelect}&is_active=eq.true&order=name.asc&limit=50${search}`)).map(mapCustomer)}
export async function searchProducts(term=''):Promise<Product[]>{const q=term.trim(),search=q?`&or=(name.ilike.*${encodeURIComponent(q)}*,code.ilike.*${encodeURIComponent(q)}*,hsn_code.ilike.*${encodeURIComponent(q)}*)`:'';return(await select<Row>('products',`select=${productSelect}&is_active=eq.true&order=name.asc&limit=100${search}`)).map(mapProduct)}
export async function getCustomer(id:string){const row=await selectOne<Row>('customers',`select=${customerSelect}&id=eq.${encodeURIComponent(id)}&is_active=eq.true`);return row?mapCustomer(row):undefined}
export async function getProduct(id:string){const row=await selectOne<Row>('products',`select=${productSelect}&id=eq.${encodeURIComponent(id)}`);return row?mapProduct(row):undefined}
function mapCustomer(r:Row):Customer{return{id:String(r.id),code:String(r.code),name:String(r.name),phone:r.phone as string|null,email:r.email as string|null,gstin:r.gstin as string|null,billingAddress:r.billingAddress as string|null,shippingAddress:r.shippingAddress as string|null,state:r.state as string|null,city:r.city as string|null,stateCode:r.stateCode as string|null,pincode:r.pincode as string|null}}
function mapProduct(r:Row):Product{return{id:String(r.id),code:String(r.code),name:String(r.name),category:String(r.category??'Biscuits'),hsn:r.hsn_code as string|null,packSize:r.packSize as string|null,unit:String(r.unit),rateMinor:Number(r.rateMinor??0),gstRateBps:Number(r.gstRateBps??0),active:Boolean(r.active??false),stockQty:Number(r.stockQty??0),reorderLevel:Number(r.reorderLevel??0),stockUnit:String(r.stockUnit??r.unit??'PCS'),shelfLocation:r.shelfLocation as string|null,costMinor:Number(r.costMinor??0)}}
