'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import './customers.css'

type Customer = { id:string; code:string; name:string; phone:string|null; email:string|null; gstin:string|null; billingAddress:string|null; shippingAddress:string|null; state:string|null; city:string|null }
type Summary = { invoiceCount:number; totalSalesMinor:number; lastPurchaseDate:string|null }

const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v/100)

export default function CustomersPage(){
 const [q,setQ]=useState(''); const [rows,setRows]=useState<Customer[]>([]); const [selected,setSelected]=useState<Customer|null>(null); const [summary,setSummary]=useState<Summary|null>(null); const [history,setHistory]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [showNew,setShowNew]=useState(false)
 const load=async(term='')=>{setLoading(true);setError('');try{const r=await fetch(`/api/customers?q=${encodeURIComponent(term)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load customers');setRows(d.customers||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load customers')}finally{setLoading(false)}}
 const open=async(c:Customer)=>{setSelected(c);setError('');const r=await fetch(`/api/customers/${c.id}`,{cache:'no-store'});const d=await r.json();if(r.ok){setSelected(d.customer);setSummary(d.summary);setHistory(d.history||[])}else setError(d.error||'Unable to load customer')}
 useEffect(()=>{void load()},[])
 const save=async(form:HTMLFormElement)=>{setSaving(true);setError('');const data=Object.fromEntries(new FormData(form).entries());try{const r=await fetch(showNew?'/api/customers/create':`/api/customers/${selected?.id}`,{method:showNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save customer');setShowNew(false);await load(q);if(d.customer)await open(d.customer)}catch(e){setError(e instanceof Error?e.message:'Unable to save customer')}finally{setSaving(false)}}
 return <main className="customers-page"><header className="customers-header"><div><small>AISWARYA FOOD PRODUCTS</small><h1>Customers</h1><p>Remember every customer and quickly return to their billing history.</p></div><div className="customer-actions"><Link href="/invoice" className="secondary">New Invoice</Link><button className="primary" onClick={()=>{setSelected(null);setShowNew(true)}}>+ Add Customer</button></div></header>
 <section className="customer-layout"><div className="customer-list-card"><div className="customer-search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q)} placeholder="Search name, code, phone, GSTIN or city…"/><button onClick={()=>load(q)}>Search</button></div>{loading?<div className="empty">Loading customers…</div>:rows.length===0?<div className="empty">No customers found.</div>:rows.map(c=><button className={`customer-item ${selected?.id===c.id?'active':''}`} key={c.id} onClick={()=>open(c)}><span><strong>{c.name}</strong><small>{c.code}{c.city?` · ${c.city}`:''}</small></span><b>{c.phone||'—'}</b></button>)}</div>
 <div className="customer-detail">{showNew||selected?<CustomerForm customer={showNew?null:selected} saving={saving} onCancel={()=>setShowNew(false)} onSave={save}/>:<div className="detail-empty"><strong>Select a customer</strong><span>Choose a customer to see their details, purchase history and total sales.</span></div>}{error&&<div className="customer-error">{error}</div>}{selected&&!showNew&&summary&&<section className="customer-stats"><article><span>Total Sales</span><strong>{money(summary.totalSalesMinor)}</strong></article><article><span>Invoices</span><strong>{summary.invoiceCount}</strong></article><article><span>Last Purchase</span><strong>{summary.lastPurchaseDate||'—'}</strong></article></section>}{selected&&!showNew&&<section className="history"><h2>Purchase History</h2>{history.length===0?<p>No invoices yet.</p>:history.map(i=><Link href={`/invoices/${i.id}`} className="history-row" key={i.id}><strong>{i.invoiceNumber}</strong><span>{i.invoiceDate}</span><span>{i.status}</span><b>{money(i.grandTotalMinor)}</b></Link>)}</section>}</div></section></main>
}

function CustomerForm({customer,saving,onCancel,onSave}:{customer:Customer|null;saving:boolean;onCancel:()=>void;onSave:(form:HTMLFormElement)=>void}){return <form className="customer-form" onSubmit={e=>{e.preventDefault();onSave(e.currentTarget)}}><div className="form-title"><div><small>{customer?'CUSTOMER PROFILE':'NEW CUSTOMER'}</small><h2>{customer?customer.name:'Add customer'}</h2></div><button type="button" className="close" onClick={onCancel}>Cancel</button></div><div className="form-grid"><label>Name<input name="name" required defaultValue={customer?.name||''}/></label><label>Customer Code<input name="code" defaultValue={customer?.code||''} placeholder="Auto-generated if blank"/></label><label>Phone<input name="phone" defaultValue={customer?.phone||''}/></label><label>Email<input name="email" type="email" defaultValue={customer?.email||''}/></label><label>GSTIN<input name="gstin" defaultValue={customer?.gstin||''}/></label><label>City<input name="city" defaultValue={customer?.city||''}/></label><label>State<input name="state" defaultValue={customer?.state||''}/></label><label>State Code<input name="stateCode" defaultValue={''}/></label><label className="wide">Billing Address<textarea name="billingAddress" defaultValue={customer?.billingAddress||''}/></label><label className="wide">Shipping Address<textarea name="shippingAddress" defaultValue={customer?.shippingAddress||''}/></label></div><button className="save" disabled={saving}>{saving?'Saving…':customer?'Save Changes':'Create Customer'}</button></form>}
