'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import './auth.css'

export default function LoginPage(){
 const router=useRouter(); const[setup,setSetup]=useState(false); const[ownerName,setOwnerName]=useState(''); const[ownerPin,setOwnerPin]=useState(''); const[staffPin,setStaffPin]=useState(''); const[pin,setPin]=useState(''); const[error,setError]=useState(''); const[busy,setBusy]=useState(false)
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>{if(d.authenticated)router.replace('/dashboard');else setSetup(!d.configured)}).catch(()=>setError('Unable to check authentication.'))},[router])
 async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{if(setup){const r=await fetch('/api/auth/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ownerName,ownerPin,staffPin:staffPin||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSetup(false);setPin(ownerPin)}else{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});const d=await r.json();if(r.status===428){setSetup(true);return}if(!r.ok)throw new Error(d.error);router.replace('/dashboard');router.refresh()}}catch(e){setError(e instanceof Error?e.message:'Something went wrong.')}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-card"><div className="auth-brand"><div className="auth-mark">A</div><div><strong>Aiswarya</strong><span>Food Products</span></div></div>{setup?<><p className="auth-eyebrow">FIRST-TIME SETUP</p><h1>Secure the billing system</h1><p className="auth-copy">Create an owner PIN. You can also create a separate staff PIN for everyday billing.</p></>:<><p className="auth-eyebrow">SECURE ACCESS</p><h1>Enter your PIN</h1><p className="auth-copy">Use your staff PIN for billing or owner PIN for settings and administration.</p></>}
 <form onSubmit={submit}>{setup&&<label>Owner name<input value={ownerName} onChange={e=>setOwnerName(e.target.value)} placeholder="Owner / administrator" autoFocus/></label>}{setup&&<label>Owner PIN<input inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} type="password" value={ownerPin} onChange={e=>setOwnerPin(e.target.value.replace(/\D/g,''))} placeholder="4–8 digits" autoComplete="new-password"/></label>}{setup&&<label>Staff PIN <span className="optional">optional</span><input inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} type="password" value={staffPin} onChange={e=>setStaffPin(e.target.value.replace(/\D/g,''))} placeholder="4–8 digits" autoComplete="new-password"/></label>}{!setup&&<label>PIN<input autoFocus inputMode="numeric" pattern="[0-9]{4,8}" maxLength={8} type="password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="Enter PIN" autoComplete="current-password"/></label>}{error&&<div className="auth-error">{error}</div>}<button disabled={busy}>{busy?'Please wait…':setup?'Create secure access':'Sign in'}</button></form><p className="auth-foot">Server-side security · Your PIN is never stored as plain text.</p></section></main>
}
