'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import './warehouse.css'

type Product={id:string;name:string;code:string;category:string;packSize:string|null;unit:string;rateMinor:number;stockQty:number;reorderLevel:number;stockUnit:string;shelfLocation:string|null}
const money=(minor:number)=>`₹${(minor/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function WarehousePage(){
 const [products,setProducts]=useState<Product[]>([]),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[role,setRole]=useState('STAFF'),[selected,setSelected]=useState<Product|null>(null),[quantity,setQuantity]=useState(''),[movement,setMovement]=useState('RECEIPT'),[reason,setReason]=useState(''),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch(`/api/warehouse?q=${encodeURIComponent(q)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load warehouse');setProducts(d.products||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load warehouse')}finally{setLoading(false)}}
 useEffect(()=>{void load();fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).then(d=>setRole(d.session?.role??'STAFF')).catch(()=>{})},[])
 const low=products.filter(p=>p.stockQty>0&&p.stockQty<=p.reorderLevel),out=products.filter(p=>p.stockQty<=0),units=products.reduce((s,p)=>s+p.stockQty,0)
 const grouped=useMemo(()=>products.reduce<Record<string,Product[]>>((a,p)=>(a[p.category]??=[]).push(p)&&a,{}),[products])
 const adjust=async()=>{if(!selected)return;setSaving(true);setError('');try{const r=await fetch('/api/warehouse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:selected.id,quantity:Number(quantity),movementType:movement,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to adjust stock');setSelected(null);setQuantity('');setReason('');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to adjust stock')}finally{setSaving(false)}}
 return <main className="warehouse-page"><header className="warehouse-hero"><div><small>OPERATIONS · STOCKROOM</small><h1>Warehouse</h1><p>See what is on the shelf, what needs replenishing, and adjust stock without touching the billing counter.</p></div><div className="warehouse-hero-actions"><Link href="/invoice">Go to Counter →</Link><Link href="/products">Product Catalogue →</Link></div></header>
 {error&&<div className="warehouse-error">{error}<button onClick={()=>void load()}>Try again</button></div>}
 <section className="warehouse-grid"><article className="warehouse-stat"><span>PRODUCTS ON SHELF</span><strong>{loading?'—':products.length}</strong><small>Active catalogue items</small></article><article className="warehouse-stat"><span>TOTAL UNITS</span><strong>{loading?'—':units.toLocaleString('en-IN')}</strong><small>Across tracked products</small></article><article className="warehouse-stat"><span>LOW STOCK</span><strong>{loading?'—':low.length}</strong><small>At or below reorder level</small></article><article className="warehouse-stat"><span>OUT OF STOCK</span><strong>{loading?'—':out.length}</strong><small>Needs attention</small></article></section>
 <section className="warehouse-layout"><div className="warehouse-card"><div className="warehouse-card-head"><div><small>SHELF VIEW</small><h2>Product shelves</h2></div><div className="warehouse-search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search biscuit, code or HSN…"/><button onClick={()=>void load()}>Search</button></div></div><div className="warehouse-shelves">{loading?<div className="warehouse-empty">Loading stockroom…</div>:products.length===0?<div className="warehouse-empty"><strong>No products yet</strong><span>Create your biscuit catalogue first, then stock it here.</span><Link href="/products">Open Products →</Link></div>:Object.entries(grouped).map(([category,items])=><section className="shelf-group" key={category}><div className="shelf-label"><span>{category}</span><small>{items.length} product{items.length===1?'':'s'}</small></div>{items.map(p=>{const status=p.stockQty<=0?'out':p.stockQty<=p.reorderLevel?'low':'ok';return <article className="shelf-product" key={p.id}><div className="shelf-icon">□</div><div><strong>{p.name}</strong><small>{p.code} · {p.packSize||'—'} · Shelf {p.shelfLocation||'not assigned'}</small></div><strong>{money(p.rateMinor)}</strong><span className={`stock-badge ${status}`}>{p.stockQty.toLocaleString('en-IN')} {p.stockUnit}</span>{role==='OWNER'&&<button className="adjust-link" onClick={()=>{setSelected(p);setQuantity('');setMovement('RECEIPT');setReason('')}}>Adjust</button>}</article>})}</section>)}</div></div>
 <aside className="warehouse-card warehouse-side"><div className="warehouse-card-head"><div><small>OPERATING RULE</small><h2>Stock control</h2></div></div><div className="warehouse-side-body"><div className="warehouse-note"><strong>Counter and warehouse are separate.</strong><p>The counter selects products and bills customers. Warehouse controls the physical shelf quantity, reorder levels and locations.</p></div><div className="stock-legend"><div><span className="stock-dot ok"/>Healthy stock</div><div><span className="stock-dot low"/>Reorder soon</div><div><span className="stock-dot out"/>Out of stock</div></div>{role==='OWNER'?<p className="warehouse-permission">You are signed in as Owner, so stock adjustments are enabled.</p>:<p className="warehouse-permission">Staff can view stock. Owner access is required to change quantities.</p>}</div></aside></section>
 {selected&&<div className="stock-overlay"><form className="stock-modal" onSubmit={e=>{e.preventDefault();void adjust()}}><div className="stock-modal-head"><div><small>STOCK ADJUSTMENT</small><h2>{selected.name}</h2><p>{selected.code} · Current stock {selected.stockQty} {selected.stockUnit}</p></div><button type="button" onClick={()=>setSelected(null)}>×</button></div><label>Movement<select value={movement} onChange={e=>setMovement(e.target.value)}><option value="RECEIPT">Stock received (+)</option><option value="RETURN">Customer return (+)</option><option value="ADJUSTMENT">Manual adjustment (+ / −)</option><option value="DAMAGE">Damage / wastage (−)</option></select></label><label>Quantity<input autoFocus type="number" step="0.001" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="e.g. 50"/></label><label>Reason<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. New production batch"/></label><div className="stock-modal-actions"><button type="button" onClick={()=>setSelected(null)}>Cancel</button><button type="submit" disabled={saving||!Number(quantity)}>{saving?'Saving…':'Update shelf stock'}</button></div></form></div>}
 </main>
}
