'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import './products.css'

type Product = { id:string; code:string; name:string; category:string; hsnCode:string|null; packSize:string|null; unit:string; defaultRateMinor:number; gstRateBps:number }
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v/100)
const categories=['Biscuits','Fried Biscuits','Bakery Biscuits','Bakery Products','Other']

export default function ProductsPage(){
 const [q,setQ]=useState(''); const [rows,setRows]=useState<Product[]>([]); const [selected,setSelected]=useState<Product|null>(null); const [showNew,setShowNew]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const load=async(term='')=>{setLoading(true);setError('');try{const r=await fetch(`/api/products?q=${encodeURIComponent(term)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load products');setRows(d.products||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load products')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const save=async(form:HTMLFormElement)=>{setSaving(true);setError('');const data=Object.fromEntries(new FormData(form).entries());try{const url=showNew?'/api/products/create':`/api/products/${selected?.id}`;const r=await fetch(url,{method:showNew?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save product');setShowNew(false);setSelected(d.product||null);await load(q)}catch(e){setError(e instanceof Error?e.message:'Unable to save product')}finally{setSaving(false)}}
 return <main className="products-page"><header className="products-header"><div><small>AISWARYA FOOD PRODUCTS · PRODUCT CATALOGUE</small><h1>Products & Rates</h1><p>Manage biscuits, fried biscuits and bakery products. Change a billing rate once and the next invoice uses the new default.</p></div><div className="product-actions"><Link href="/invoice" className="secondary">New Invoice</Link><button className="primary" onClick={()=>{setSelected(null);setShowNew(true)}}>+ Add Product</button></div></header>
 <section className="product-layout"><div className="product-list-card"><div className="product-search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(q)} placeholder="Search product, code, HSN or pack…"/><button onClick={()=>load(q)}>Search</button></div>{loading?<div className="empty">Loading products…</div>:rows.length===0?<div className="empty"><strong>No products found</strong><span>Add a product to make it available for billing.</span></div>:rows.map(p=><button className={`product-item ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>{setSelected(p);setShowNew(false)}}><span><strong>{p.name}</strong><small>{p.category} · {p.code}{p.packSize?` · ${p.packSize}`:''}</small></span><b>{money(p.defaultRateMinor)}</b></button>)}</div>
 <div className="product-detail">{showNew||selected?<ProductForm product={showNew?null:selected} saving={saving} onCancel={()=>{setShowNew(false);if(!selected)setSelected(null)}} onSave={save}/>:<div className="detail-empty"><strong>Choose a product</strong><span>Edit price, GST, pack size or category from one screen.</span></div>}{error&&<div className="product-error">{error}</div>}</div></section></main>
}

function ProductForm({product,saving,onCancel,onSave}:{product:Product|null;saving:boolean;onCancel:()=>void;onSave:(form:HTMLFormElement)=>void}){return <form className="product-form" onSubmit={e=>{e.preventDefault();onSave(e.currentTarget)}}><div className="form-title"><div><small>{product?'EDIT PRODUCT':'NEW PRODUCT'}</small><h2>{product?product.name:'Add product'}</h2></div><button type="button" className="close" onClick={onCancel}>Cancel</button></div><div className="form-grid"><label>Name<input name="name" required defaultValue={product?.name||''}/></label><label>Product Code<input name="code" required defaultValue={product?.code||''} placeholder="e.g. BIS-1001"/></label><label>Category<select name="category" defaultValue={product?.category||'Biscuits'}>{categories.map(category=><option key={category}>{category}</option>)}</select></label><label>HSN Code<input name="hsnCode" defaultValue={product?.hsnCode||''}/></label><label>Pack Size<input name="packSize" defaultValue={product?.packSize||''} placeholder="e.g. 100 g"/></label><label>Unit<select name="unit" defaultValue={product?.unit||'PCS'}><option>PCS</option><option>BOX</option><option>PACK</option><option>KG</option><option>GRAM</option><option>DOZEN</option></select></label><label>Default Rate (₹)<input name="defaultRate" type="number" min="0" step="0.01" required defaultValue={product?(product.defaultRateMinor/100).toFixed(2):''}/></label><label>GST Rate (%)<input name="gstRate" type="number" min="0" max="100" step="0.01" required defaultValue={product?(product.gstRateBps/100).toFixed(2):'0'}/></label></div><div className="form-note"><strong>Billing rule:</strong> this rate is the product default for new invoice lines. Finalized invoices keep their own rate/GST snapshot, so changing this later will not rewrite old bills.</div><button className="save" disabled={saving}>{saving?'Saving…':product?'Save Product & Rate':'Create Product'}</button></form>}
