'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import './dashboard.css'

type DashboardData={today:string;summary:{todaySalesMinor:number;todayInvoiceCount:number;draftCount:number;cancelledCount:number};counts:{customerCount:number;productCount:number;failedNotificationCount:number};recentInvoices:{id:string;invoiceNumber:string;invoiceDate:string;status:string;grandTotalMinor:number;customerName:string}[];topCustomers:{id:string;name:string;code:string;invoiceCount:number;totalSalesMinor:number}[]}
const money=(minor:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(minor/100)
const dateLabel=(value:string)=>new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T00:00:00`))

export default function DashboardPage(){
  const router=useRouter();const[data,setData]=useState<DashboardData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[role,setRole]=useState('STAFF')
  const load=async()=>{setLoading(true);setError('');try{const response=await fetch('/api/dashboard',{cache:'no-store'});if(!response.ok)throw new Error('Unable to load dashboard');setData(await response.json())}catch(err){setError(err instanceof Error?err.message:'Unable to load dashboard')}finally{setLoading(false)}}
  useEffect(()=>{void load();fetch('/api/auth/me',{cache:'no-store'}).then(r=>r.json()).then(d=>setRole(d.session?.role??'STAFF')).catch(()=>{})},[])
  const logout=async()=>{await fetch('/api/auth/logout',{method:'POST'});router.replace('/login');router.refresh()}
  return <main className="dashboard-shell"><div className="dashboard-frame">
    <header className="dashboard-header"><div className="brand-lockup"><div className="brand-orb">A</div><div><p className="eyebrow">AISWARYA FOOD PRODUCTS</p><h1>Billing Desk</h1><p className="muted">Counter-first workspace for biscuits, customers and daily operations.</p></div></div><div className="header-actions"><span className="session-badge"><span className="status-dot"/>{role==='OWNER'?'Owner':'Staff'}</span>{role==='OWNER'&&<Link className="secondary-button" href="/settings">Settings</Link>}<button className="secondary-button" onClick={()=>void load()} disabled={loading}>↻ Refresh</button><button className="secondary-button" onClick={()=>void logout()}>Lock</button></div></header>
    {error&&<div className="error-banner">{error}<button onClick={()=>void load()}>Try again</button></div>}
    <section className="welcome-strip"><div><span className="section-kicker">COUNTER</span><h2>Ready to make a bill?</h2><p>Pick a customer, put products into the basket, review the total and finalize.</p></div><Link href="/invoice" className="hero-invoice-button"><span className="hero-plus">＋</span><span><strong>START NEW BILL</strong><small>Open the checkout counter</small></span><b>→</b></Link></section>
    <section className="metric-grid" aria-label="Billing summary"><Metric label="Today&apos;s Sales" value={data?money(data.summary.todaySalesMinor):'—'} detail={data?dateLabel(data.today):'Loading'} accent/><Metric label="Bills Today" value={data?String(data.summary.todayInvoiceCount):'—'} detail="Finalized invoices" icon="▤"/><Metric label="Customers" value={data?String(data.counts.customerCount):'—'} detail="Active customers" icon="◎"/><Metric label="Products" value={data?String(data.counts.productCount):'—'} detail="Catalogue items" icon="□"/></section>
    <section className="quick-grid dashboard-workspaces" aria-label="Business workspaces"><Link href="/invoice" className="quick-card workspace-counter"><span className="quick-icon">＋</span><span><strong>COUNTER</strong><small>Make a new customer bill</small></span><b>Open →</b></Link><Link href="/invoices" className="quick-card"><span className="quick-icon">▤</span><span><strong>BILLS</strong><small>Search, print and reopen past bills</small></span><b>Open →</b></Link><Link href="/customers" className="quick-card"><span className="quick-icon">◎</span><span><strong>CUSTOMERS</strong><small>Customers, balances and history</small></span><b>Open →</b></Link><Link href="/products" className="quick-card"><span className="quick-icon">□</span><span><strong>PRODUCTS</strong><small>Catalogue, prices and quick edits</small></span><b>Open →</b></Link><Link href="/warehouse" className="quick-card"><span className="quick-icon">▥</span><span><strong>WAREHOUSE</strong><small>Shelves, stock and reorder levels</small></span><b>Open →</b></Link></section>
    <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><div><span className="section-kicker">ACTIVITY</span><h2>Recent Bills</h2><p>Latest billing activity</p></div><Link href="/invoices">View all →</Link></div><div className="invoice-list">{!loading&&data?.recentInvoices.length===0&&<div className="empty"><span className="empty-icon">▤</span><strong>No bills yet</strong><span>Create your first customer bill to see activity here.</span><Link href="/invoice">Start counter →</Link></div>}{data?.recentInvoices.map(invoice=><Link className="invoice-row" href={`/invoices/${invoice.id}`} key={invoice.id}><div><strong>{invoice.invoiceNumber}</strong><span>{invoice.customerName}</span></div><div className="invoice-row-right"><strong>{money(invoice.grandTotalMinor)}</strong><span className={`status ${invoice.status.toLowerCase()}`}>{invoice.status}</span></div></Link>)}{loading&&<div className="loading-lines"><i/><i/><i/></div>}</div></section><section className="panel"><div className="panel-heading"><div><span className="section-kicker">CUSTOMERS</span><h2>Top Customers</h2><p>By finalized sales</p></div></div><div className="customer-list">{!loading&&data?.topCustomers.length===0&&<div className="empty"><span className="empty-icon">◎</span><strong>No customer records yet</strong><span>Customers will appear here after billing.</span></div>}{data?.topCustomers.map((customer,index)=><div className="customer-row" key={customer.id}><span className="rank">{index+1}</span><div><strong>{customer.name}</strong><span>{customer.code} · {customer.invoiceCount} invoice{customer.invoiceCount===1?'':'s'}</span></div><strong>{money(customer.totalSalesMinor)}</strong></div>)}{loading&&<div className="loading-lines"><i/><i/><i/></div>}</div></section></div>
    {data&&data.counts.failedNotificationCount>0&&<div className="notice-banner"><strong>{data.counts.failedNotificationCount} notification{data.counts.failedNotificationCount===1?'':'s'} failed.</strong><span>Email/WhatsApp delivery can be retried once provider credentials are configured.</span></div>}<footer className="dashboard-footer"><span>AISWARYA FOOD PRODUCTS</span><span>Billing Desk · Online operations</span></footer>
  </div></main>
}
function Metric({label,value,detail,accent=false,icon}:{label:string;value:string;detail:string;accent?:boolean;icon?:string}){return <article className={`metric-card ${accent?'metric-accent':''}`}><div className="metric-top"><span>{label}</span>{icon&&<i>{icon}</i>}</div><strong>{value}</strong><small>{detail}</small></article>}
