'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import './print.css'

type Item={product_name:string;product_code:string;hsn_code:string|null;pack_size:string|null;unit:string;quantity:string;rate_minor:number;taxable_minor:number;cgst_minor:number;sgst_minor:number;igst_minor:number;line_total_minor:number}
type Invoice={invoice_number:string;invoice_date:string;status:string;customer_name:string;customer_code:string;customer_phone:string|null;customer_email:string|null;customer_gstin:string|null;billing_address:string|null;shipping_address:string|null;customer_city:string|null;customer_state:string|null;customer_pincode:string|null;subtotal_minor:number;discount_minor:number;freight_minor:number;other_charges_minor:number;taxable_value_minor:number;cgst_minor:number;sgst_minor:number;igst_minor:number;round_off_minor:number;grand_total_minor:number;notes:string|null}
type Company={name:string;tagline:string;address:string;gstin:string;fssai:string;phone:string;email:string;website:string;logoUrl:string;bankAccountName:string;bankName:string;bankAccountNumber:string;bankIfsc:string;bankBranch:string;terms:string;footerMessage:string;footerTagline:string;authorizedSignatory:string;defaultGstMode:'INTRA'|'INTER'}

const amount=(v:number)=>(v/100).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})
const money=(v:number)=>`₹${amount(v)}`
function words(v:number){const n=Math.round(v/100);if(n===0)return'Zero Rupees Only';const ones=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];const two=(x:number)=>x<20?ones[x]:tens[Math.floor(x/10)]+(x%10?' '+ones[x%10]:'');let x=n;const p:string[]=[];if(Math.floor(x/10000000)){p.push(`${two(Math.floor(x/10000000))} Crore`);x%=10000000}if(Math.floor(x/100000)){p.push(`${two(Math.floor(x/100000))} Lakh`);x%=100000}if(Math.floor(x/1000)){p.push(`${two(Math.floor(x/1000))} Thousand`);x%=1000}if(Math.floor(x/100)){p.push(`${ones[Math.floor(x/100)]} Hundred`);x%=100}if(x)p.push(two(x));return`${p.join(' ')} Rupees Only`}
function dateLabel(v:string){const d=new Date(`${v}T00:00:00`);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}
function stateLabel(v:string|null){return v||'—'}

export default function InvoicePrintPage(){const{ id }=useParams<{id:string}>();const[data,setData]=useState<{invoice:Invoice;items:Item[]}|null>(null);const[company,setCompany]=useState<Company|null>(null);const[error,setError]=useState('');useEffect(()=>{Promise.all([fetch(`/api/invoices/${id}`),fetch('/api/settings/company')]).then(async([invoiceRes,settingsRes])=>{const invoiceData=await invoiceRes.json();const settingsData=await settingsRes.json();if(!invoiceRes.ok)throw new Error(invoiceData.error);if(!settingsRes.ok)throw new Error(settingsData.error);setData(invoiceData);setCompany(settingsData.settings)}).catch(e=>setError(e.message||'Unable to load invoice'))},[id]);if(error)return<main className="print-shell"><div className="print-error">{error}</div></main>;if(!data||!company)return<main className="print-shell"><div className="print-loading">Loading invoice…</div></main>;const i=data.invoice;const totalQuantity=data.items.reduce((s,x)=>s+Number(x.quantity||0),0);const interstate=i.igst_minor>0;const addressLines=company.address.split(/\r?\n/).filter(Boolean);const terms=company.terms.split(/\r?\n/).filter(Boolean);return <main className="print-shell"><div className="print-actions"><Link href="/invoices">← Invoice History</Link><Link className="settings-link" href="/settings">Company Settings</Link><button onClick={()=>window.print()}>Print / Save PDF</button></div><article className="invoice-paper">
<header className="invoice-head"><div className="brand-block">{company.logoUrl?<img className="company-logo" src={company.logoUrl} alt="Company logo"/>:<div className="brand-mark" aria-hidden="true"><span/><span/><span/><span/></div>}<div><div className="brand-name">Aiswarya</div><div className="brand-subname">Food Products</div><div className="tagline">{company.tagline}</div></div></div><div className="company-block"><strong>{company.name}</strong>{addressLines.map((x,n)=><span key={`${x}-${n}`}>{x}</span>)}{company.gstin&&<span>GSTIN: {company.gstin}</span>}{company.fssai&&<span>FSSAI Lic. No: {company.fssai}</span>}</div><div className="tax-block"><h1>TAX INVOICE</h1><span>Original for Recipient</span><dl><div><dt>Invoice No.</dt><dd>{i.invoice_number}</dd></div><div><dt>Invoice Date</dt><dd>{dateLabel(i.invoice_date)}</dd></div><div><dt>Due Date</dt><dd>{dateLabel(i.invoice_date)}</dd></div><div><dt>Place of Supply</dt><dd>{stateLabel(i.customer_state)}</dd></div></dl></div></header>
<section className="party-grid"><div className="party-card"><b>BILL TO</b><strong>{i.customer_name}</strong>{i.billing_address&&<span>{i.billing_address}</span>}<span>{[i.customer_city,i.customer_state,i.customer_pincode].filter(Boolean).join(' – ')||'—'}</span><span>GSTIN: {i.customer_gstin||'—'}</span><span>State: {stateLabel(i.customer_state)}</span></div><div className="party-card"><b>SHIP TO</b><strong>{i.customer_name}</strong><span>{i.shipping_address||i.billing_address||'—'}</span><span>{[i.customer_city,i.customer_state,i.customer_pincode].filter(Boolean).join(' – ')||'—'}</span><span>State: {stateLabel(i.customer_state)}</span></div></section>
<table className="items-table"><thead><tr><th>#</th><th>Product Description</th><th>HSN Code</th><th>Pack Size</th><th>Quantity<br/>(Units)</th><th>Rate<br/>(₹)</th><th>Amount<br/>(₹)</th></tr></thead><tbody>{data.items.map((x,n)=><tr key={`${x.product_code}-${n}`}><td>{n+1}</td><td>{x.product_name}</td><td>{x.hsn_code||'—'}</td><td>{x.pack_size||'—'}</td><td>{Number(x.quantity).toLocaleString('en-IN')}</td><td>{amount(x.rate_minor)}</td><td>{amount(x.line_total_minor)}</td></tr>)}</tbody></table>
<section className="totals-area"><div className="quantity-total"><span>Total Quantity</span><strong>{totalQuantity.toLocaleString('en-IN')}</strong></div><div className="totals-card"><div><span>Subtotal</span><strong>{amount(i.subtotal_minor)}</strong></div>{i.discount_minor>0&&<div><span>Discount</span><strong>- {amount(i.discount_minor)}</strong></div>}<div><span>Freight / Transport Charges</span><strong>{amount(i.freight_minor)}</strong></div><div><span>Other Charges</span><strong>{amount(i.other_charges_minor)}</strong></div><div className="taxable-row"><span>Taxable Value</span><strong>{amount(i.taxable_value_minor)}</strong></div>{!interstate&&i.cgst_minor>0&&<div><span>CGST</span><strong>{amount(i.cgst_minor)}</strong></div>}{!interstate&&i.sgst_minor>0&&<div><span>SGST</span><strong>{amount(i.sgst_minor)}</strong></div>}{interstate&&i.igst_minor>0&&<div><span>IGST</span><strong>{amount(i.igst_minor)}</strong></div>}{i.round_off_minor!==0&&<div><span>Round Off</span><strong>{amount(i.round_off_minor)}</strong></div>}<div className="grand-row"><span>Grand Total</span><strong>{money(i.grand_total_minor)}</strong></div></div></section>
<section className="words-box"><b>Amount in Words</b><strong>{words(i.grand_total_minor)}</strong></section>
<section className="bottom-grid"><div><h3>Bank Details</h3><dl className="bank-details">{[['Account Name',company.bankAccountName],['Bank Name',company.bankName],['Account No.',company.bankAccountNumber],['IFSC Code',company.bankIfsc],['Branch',company.bankBranch]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'—'}</dd></div>)}</dl></div><div><h3>Terms &amp; Conditions</h3><ol className="terms-list">{terms.map((x,n)=><li key={`${x}-${n}`}>{x.replace(/^\d+[.)]\s*/,'')}</li>)}</ol>{i.notes&&<p className="invoice-note">{i.notes}</p>}</div><div className="authorised"><h3>For {company.name}</h3><div className="signature-space"></div><div className="signature-line">{company.authorizedSignatory}</div></div></section>
<footer className="invoice-footer"><div><strong>{company.footerMessage}</strong><span>{company.footerTagline}</span></div><div className="contact-footer">{company.phone&&<span>☎ {company.phone}</span>}{company.email&&<span>✉ {company.email}</span>}{company.website&&<span>◉ {company.website}</span>}</div></footer></article></main>}
