import { NextResponse } from 'next/server'
import { requireApiAuth } from '@/lib/auth/api'
import { select, selectOne, update, insert } from '@/lib/db/client'
import crypto from 'node:crypto'
export const runtime='nodejs'
type Params={params:Promise<{id:string}>}
const customerSelect='id,code,name,phone,email,gstin,billingAddress:billing_address,shippingAddress:shipping_address,state,stateCode:state_code,city,pincode'
export async function GET(_:Request,{params}:Params){const guard=await requireApiAuth();if(guard.response)return guard.response;const{id}=await params,customer=await selectOne('customers',`select=${customerSelect}&id=eq.${encodeURIComponent(id)}&is_active=eq.true`);if(!customer)return NextResponse.json({error:'Customer not found'},{status:404});const history=await select('invoices',`select=id,invoiceNumber:invoice_number,invoiceDate:invoice_date,status,grandTotalMinor:grand_total_minor&customer_id=eq.${encodeURIComponent(id)}&order=invoice_date.desc,created_at.desc&limit=100`);const rows=await select<any>('invoices',`select=status,grand_total_minor,invoice_date&customer_id=eq.${encodeURIComponent(id)}`),finalized=rows.filter(r=>r.status==='FINALIZED');return NextResponse.json({customer,summary:{invoiceCount:rows.length,totalSalesMinor:finalized.reduce((s,r)=>s+Number(r.grand_total_minor||0),0),lastPurchaseDate:finalized.map(r=>r.invoice_date).sort().pop()??null},history})}
export async function PATCH(request:Request,{params}:Params){const guard=await requireApiAuth();if(guard.response)return guard.response;const{id}=await params,body=await request.json(),existing=await selectOne('customers',`select=id&is_active=eq.true&id=eq.${encodeURIComponent(id)}`);if(!existing)return NextResponse.json({error:'Customer not found'},{status:404});const allowed=['name','phone','email','gstin','billingAddress','shippingAddress','state','stateCode','city','pincode'] as const;if(!allowed.some(k=>body[k]!==undefined))return NextResponse.json({error:'No fields to update'},{status:400});if(body.name!==undefined&&!String(body.name).trim())return NextResponse.json({error:'Customer name is required'},{status:400});const patch:any={};for(const key of allowed)if(body[key]!==undefined){const col=key.replace(/[A-Z]/g,m=>`_${m.toLowerCase()}`);patch[col]=String(body[key]).trim()||null}if(patch.gstin)patch.gstin=patch.gstin.toUpperCase();await update('customers',`id=eq.${encodeURIComponent(id)}`,patch);await insert('audit_logs',{id:crypto.randomUUID(),actor:guard.session?.role??'STAFF',action:'UPDATE',entity_type:'CUSTOMER',entity_id:id,metadata_json:JSON.stringify({fields:allowed.filter(k=>body[k]!==undefined)})});const customer=await selectOne('customers',`select=${customerSelect}&id=eq.${encodeURIComponent(id)}`);return NextResponse.json({customer})}
