'use client'
import { FormEvent,useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import './settings.css'
type Settings=Record<string,string>
const groups=[
 {title:'Company identity',fields:[['name','Company name'],['tagline','Tagline'],['address','Address'],['gstin','GSTIN'],['fssai','FSSAI / License No.']]},
 {title:'Business profile',fields:[['businessDescription','Business description'],['productRange','Product range'],['workingHours','Working hours']]},
 {title:'Contact',fields:[['phone','Phone'],['email','Email'],['website','Website'],['logoUrl','Logo URL']]},
 {title:'Bank details',fields:[['bankAccountName','Account name'],['bankName','Bank name'],['bankAccountNumber','Account number'],['bankIfsc','IFSC code'],['bankBranch','Branch']]},
 {title:'Invoice footer',fields:[['authorizedSignatory','Authorized signatory'],['footerMessage','Footer message'],['footerTagline','Footer tagline'],['terms','Terms & conditions']]}
]
const textareas=new Set(['address','businessDescription','productRange','workingHours','terms'])
export default function SettingsPage(){const router=useRouter();const[settings,setSettings]=useState<Settings>({});const[status,setStatus]=useState('');const[auth,setAuth]=useState({ownerName:'',ownerPin:'',staffPin:''});const[authStatus,setAuthStatus]=useState('');useEffect(()=>{Promise.all([fetch('/api/settings/company'),fetch('/api/auth/me')]).then(async([a,b])=>{const company=await a.json(),me=await b.json();if(me.session?.role!=='OWNER'){router.replace('/dashboard');return}setSettings(company.settings??{});setAuth(x=>({...x,ownerName:me.session?.name??''}))}).catch(()=>setStatus('Unable to load settings.'))},[router]);const update=(key:string,value:string)=>setSettings(s=>({...s,[key]:value}));async function save(e:FormEvent){e.preventDefault();setStatus('Saving…');const res=await fetch('/api/settings/company',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});const d=await res.json();setStatus(res.ok?'Saved successfully.':(d.error??'Unable to save settings.'));if(res.ok)setSettings(d.settings)}async function savePins(e:FormEvent){e.preventDefault();setAuthStatus('Saving…');if(!auth.ownerPin){setAuthStatus('Enter a new owner PIN.');return}const res=await fetch('/api/auth/pins',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ownerName:auth.ownerName,ownerPin:auth.ownerPin,staffPin:auth.staffPin||undefined})});const d=await res.json();setAuthStatus(res.ok?'Access PINs updated.':(d.error??'Unable to update PINs.'));if(res.ok)setAuth(x=>({...x,ownerPin:'',staffPin:''}))}
return <main className="settings-page"><div className="settings-header"><div><p className="eyebrow">SETTINGS · OWNER</p><h1>Company & Invoice Settings</h1><p>Official business information is stored locally and used by the billing and A4 invoice system.</p></div><a href="/dashboard" className="secondary-button">← Dashboard</a></div><form onSubmit={save}>{groups.map(group=><section className="settings-card" key={group.title}><h2>{group.title}</h2><div className="settings-grid">{group.fields.map(([key,label])=><label key={key} className={textareas.has(key)?'wide':''}>{label}{textareas.has(key)?<textarea rows={key==='businessDescription'?5:4} value={settings[key]??''} onChange={e=>update(key,e.target.value)} placeholder={label}/>:<input value={settings[key]??''} onChange={e=>update(key,e.target.value)} placeholder={label}/>}</label>)}</div></section>)}<section className="settings-card"><h2>Tax defaults</h2><label className="select-field">Default GST mode<select value={settings.defaultGstMode??'INTRA'} onChange={e=>update('defaultGstMode',e.target.value)}><option value="INTRA">Intra-state — CGST + SGST</option><option value="INTER">Inter-state — IGST</option></select></label><p className="hint">Default for new billing flows. Final GST treatment should be confirmed with the business accountant.</p></section><div className="save-bar"><span className={status.includes('success')?'success':''}>{status}</span><button type="submit">Save Company Settings</button></div></form><form className="settings-card security-card" onSubmit={savePins}><h2>Security & access</h2><p className="hint">PINs are salted and hashed locally. Staff can bill; the owner PIN unlocks company administration.</p><div className="settings-grid"><label>Owner name<input value={auth.ownerName} onChange={e=>setAuth(x=>({...x,ownerName:e.target.value}))}/></label><label>New owner PIN<input inputMode="numeric" type="password" maxLength={8} pattern="[0-9]{4,8}" value={auth.ownerPin} onChange={e=>setAuth(x=>({...x,ownerPin:e.target.value.replace(/\D/g,'')}))} placeholder="4–8 digits"/></label><label>New staff PIN <span className="hint-inline">leave blank to disable</span><input inputMode="numeric" type="password" maxLength={8} pattern="[0-9]{4,8}" value={auth.staffPin} onChange={e=>setAuth(x=>({...x,staffPin:e.target.value.replace(/\D/g,'')}))} placeholder="4–8 digits"/></label></div><div className="save-bar"><span className={authStatus.includes('updated')?'success':''}>{authStatus}</span><button type="submit">Update Access PINs</button></div></form></main>}
